services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - qbick-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '15432:80'

  maildev:
    build:
      context: .
      dockerfile: dockerfiles/maildev/Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped

# api:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   ports:
#     - ${APP_PORT}:${APP_PORT}

volumes:
  qbick-db:
